### ISSUE TITLE
where code.

### ISSUE THREAD

**Issue by nitrogenez** [foresle/potomstvo#1]
![58eyvu.png](https://user-images.githubusercontent.com/112193680/231465058-8a0906ef-08ca-4572-86d6-e4ebe349d9ea.png)

**Comment by foresle** [comment]
Oh no, someone stole the code!!!

**Comment by nitrogenez** [comment]
sadness..........

**Comment by nitrogenez** [comment]
oh wait, we need to find the thieves!!!!!!!
